# Generated by Django 5.2.8 on 2026-01-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão devolução'),
        ),
    ]
