# Generated by Django 5.2.8 on 2026-01-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_numero_paginas'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_livros/'),
        ),
    ]
